apiVersion: v1
kind: Service
metadata:
  name: poly-orchestrator
  namespace: poly-orchestrator
  labels:
    app.kubernetes.io/name: poly-orchestrator
spec:
  selector:
    app: poly-orchestrator
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
